### Read all users
GET http://127.0.0.1:4000/user-api/users

###Read user by ObjectID
GET http://127.0.0.1:4000/user-api/users/697dba818bb0bf3be4f66cac



###Create user
POST http://127.0.0.1:4000/user-api/users
Content-Type: application/json

{
    "username":"manasa",
    "password":"manasa",
    "age":20
}



###Update user
PUT http://127.0.0.1:4000/user-api/users/697dbc67a0ad5778d8a394ef
Content-Type: application/json

{
    "username":"manasa",
    "password":"manasa",
    "age":17
}


###Delete user by ObjectID
DELETE http://127.0.0.1:4000/user-api/users/697dbc67a0ad5778d8a394ef






###Product 

##read all products
GET http://127.0.0.1:4000/product-api/products


###read product by pid
GET http://127.0.0.1:4000/product-api/products/697dd08f0539479931edef2f


###create product
POST http://127.0.0.1:4000/product-api/products
Content-Type: application/json

{
    "pid":100,
    "productName":"bat",
    "price":999
}

###modify object
PUT http://127.0.0.1:4000/product-api/products/697dd08f0539479931edef2f
Content-Type: application/json

{
    "pid":100,
    "productName":"ball",
    "price":999
}